def add numbers()
res=int(e1.get())+ int(e2.get())
res1=int(e1.get())- int(e2.get())
res2=int(e1.get()) *int(e2.get())
res3=int(e1.get())/int(e2.get())
myTextset(res)
myText1.set(res)
myText2.set(res)
myText3.set(res)
result.config(Text variable=myText)
result1.config(Text variable=myText1)
result2.config(Text variable=myText2)
result3.config(text variable=MyText3)
master=TK()
master geometry(400*400)r
myText=String var()
myText1=String var()
myText2=String var()
myText3=String var()
lable(master,text="first").grid(row=0.sticky=W)
lable(master,text="second").grid(row=1.sticky=W)
lable(master,text="third").grid(row=2.sticky=W)
lable(master,text="result").grid(row=3.sticky=W)
result=lable(master,text="add")
result.grid(row=3,column=1.sticky=W)
result1=lable(master,text="sub")
result.grid(row=3,column=2.sticky=W)
result2=lable(master,text="mul")
result.grid(row=3,column=3.sticky=W)
result3=lable(master,text"div")
result.grid(row=3,column=4.sticky=W)
c1=Entry(master)
c2=Entry(master)
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
b=Button(master,text="calculate"command=add numbers)
b.grid(row=0,column=2,column pan=2,rows pan=2,sticky=W+E+N+S.padx=5,pady=5)
mainloop()

